# Generated by Django 3.0.5 on 2020-07-20 13:45

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Chapter_Name', models.CharField(max_length=200)),
                ('Description', models.TextField()),
                ('standard', models.IntegerField()),
                ('parent', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='children', to='JC.Category')),
            ],
            options={
                'verbose_name_plural': 'Categories',
                'unique_together': {('Chapter_Name', 'parent')},
            },
        ),
    ]
