# Generated by Django 3.0.5 on 2020-07-20 14:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('JC', '0002_lectures'),
    ]

    operations = [
        migrations.AlterField(
            model_name='lectures',
            name='videofile',
            field=models.FileField(max_length=500, null=True, upload_to='videos/', verbose_name=''),
        ),
    ]
