# Generated by Django 3.0.5 on 2020-07-22 07:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('JC', '0004_auto_20200720_2026'),
    ]

    operations = [
        migrations.AlterField(
            model_name='lecture',
            name='assignment',
            field=models.FileField(blank=True, max_length=500, null=True, upload_to='assignment/', verbose_name='Assignment'),
        ),
        migrations.AlterField(
            model_name='lecture',
            name='videofile',
            field=models.FileField(blank=True, max_length=500, null=True, upload_to='videos/', verbose_name='video'),
        ),
    ]
