# Generated by Django 3.0.5 on 2020-07-22 15:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('JC', '0006_auto_20200722_1241'),
    ]

    operations = [
        migrations.AlterField(
            model_name='lecture',
            name='assignment',
            field=models.FileField(blank=True, default='#', max_length=500, null=True, upload_to='assignment/', verbose_name='Assignment'),
        ),
    ]
