# Generated by Django 3.0.5 on 2020-07-22 15:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('JC', '0007_auto_20200722_2055'),
    ]

    operations = [
        migrations.AlterField(
            model_name='lecture',
            name='assignment',
            field=models.FileField(blank=True, default='http://ncert.nic.in/textbook/textbook.htm?kemh1=0-16', max_length=500, null=True, upload_to='assignment/', verbose_name='Assignment'),
        ),
    ]
